<a href="https://colab.research.google.com/github/AEmreELP/ML_Course/blob/main/Fish_Gender_Check.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORTING TO DEPENDENCIES

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
datas = pd.read_excel('/content/drive/MyDrive/DataSets/mezgit_with_gender/mezgit_genders.xlsx')

In [ ]:
print(datas)

     LT (cm)  LF (cm)  BH (cm)  W (gr) Sex  Month
0       12.9    14.82      1.8   14.82   E  Kasim
1       12.4    15.75      2.3   15.75   E  Kasim
2       13.0    16.10      2.1   16.30   D  Kasim
3       13.5    18.30      2.4   19.09   D  Kasim
4       13.6    20.02      2.5   20.71   D  Kasim
..       ...      ...      ...     ...  ..    ...
946     14.0    13.80      2.3   19.80   D  Nisan
947     13.3    13.10      2.8   18.90   D  Nisan
948     14.3    14.00      2.6   20.00   D  Nisan
949     13.4    13.20      2.2   17.90   E  Nisan
950     15.5    15.40      3.0   26.40   E  Nisan

[951 rows x 6 columns]


In [ ]:
datas = datas.drop(["Month"], axis=1)

In [ ]:
print(datas)
datas.describe()

     LT (cm)  LF (cm)  BH (cm)  W (gr) Sex
0       12.9    14.82      1.8   14.82   E
1       12.4    15.75      2.3   15.75   E
2       13.0    16.10      2.1   16.30   D
3       13.5    18.30      2.4   19.09   D
4       13.6    20.02      2.5   20.71   D
..       ...      ...      ...     ...  ..
946     14.0    13.80      2.3   19.80   D
947     13.3    13.10      2.8   18.90   D
948     14.3    14.00      2.6   20.00   D
949     13.4    13.20      2.2   17.90   E
950     15.5    15.40      3.0   26.40   E

[951 rows x 5 columns]


LT (cm)     LF (cm)     BH (cm)      W (gr)
count  951.000000  951.000000  951.000000  951.000000
mean    12.684669   12.998707    2.084448   15.735221
std      1.598503    4.111869    0.360251    5.805375
min      6.400000    6.200000    0.900000    1.850000
25%     11.900000   11.600000    1.900000   12.205000
50%     12.800000   12.700000    2.000000   15.360000
75%     13.600000   13.700000    2.300000   18.830000
max     18.000000  111.900000    3.500000   38.400000

In [ ]:
datas['Sex'] = datas['Sex'].replace({'D': 0, 'E': 1})

In [ ]:
datas['Sex'].value_counts()

Sex
0    517
1    362
-     72
Name: count, dtype: int64

In [ ]:
datas_clean = datas[datas["Sex"] != "-"]
print(datas_clean)

     LT (cm)  LF (cm)  BH (cm)  W (gr) Sex
0       12.9    14.82      1.8   14.82   1
1       12.4    15.75      2.3   15.75   1
2       13.0    16.10      2.1   16.30   0
3       13.5    18.30      2.4   19.09   0
4       13.6    20.02      2.5   20.71   0
..       ...      ...      ...     ...  ..
946     14.0    13.80      2.3   19.80   0
947     13.3    13.10      2.8   18.90   0
948     14.3    14.00      2.6   20.00   0
949     13.4    13.20      2.2   17.90   1
950     15.5    15.40      3.0   26.40   1

[879 rows x 5 columns]


In [ ]:
datas_clean['Sex'].value_counts()

Sex
0    517
1    362
Name: count, dtype: int64

In [ ]:
X = datas_clean.drop(columns = 'Sex', axis=1)
Y = datas_clean['Sex']
print(X)
print(Y)


     LT (cm)  LF (cm)  BH (cm)  W (gr)
0       12.9    14.82      1.8   14.82
1       12.4    15.75      2.3   15.75
2       13.0    16.10      2.1   16.30
3       13.5    18.30      2.4   19.09
4       13.6    20.02      2.5   20.71
..       ...      ...      ...     ...
946     14.0    13.80      2.3   19.80
947     13.3    13.10      2.8   18.90
948     14.3    14.00      2.6   20.00
949     13.4    13.20      2.2   17.90
950     15.5    15.40      3.0   26.40

[879 rows x 4 columns]
0      1
1      1
2      0
3      0
4      0
      ..
946    0
947    0
948    0
949    1
950    1
Name: Sex, Length: 879, dtype: object


In [ ]:
scaler = StandardScaler()
scaler.fit(X)
standardized_data = scaler.transform(X)
print(standardized_data)

[[ 0.00285273  0.68111416 -0.99911968 -0.28081285]
 [-0.35742781  1.05698357  0.52341109 -0.11082357]
 [ 0.07490884  1.1984398  -0.08560122 -0.01029227]
 ...
 [ 1.01163825  0.34970242  1.43692956  0.66600919]
 [ 0.36313328  0.0263739   0.21890494  0.28216242]
 [ 1.87631156  0.91552734  2.65495418  1.83582793]]


In [ ]:
classifier = svm.SVC(kernel='linear')
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [ ]:
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print(training_data_accuracy)

0.5874822190611664


In [ ]:
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print(test_data_accuracy)

0.5909090909090909


In [ ]:
X_test_prediction = np.where(X_test_prediction == 'D', 0,
                             np.where(X_test_prediction == 'E', 1, X_test_prediction))

# Convert to float type
X_test_prediction = X_test_prediction.astype(float)

# Do the same for Y_test if needed
if isinstance(Y_test, np.ndarray) and (Y_test == 'D').any() or (Y_test == 'E').any():
    Y_test = np.where(Y_test == 'D', 0, np.where(Y_test == 'E', 1, Y_test))
    Y_test = Y_test.astype(float)
elif isinstance(Y_test, pd.Series):
    Y_test = Y_test.replace({'D': 0, 'E': 1}).astype(float)

# Now calculate r2_score
r2 = r2_score(Y_test, X_test_prediction)
print(r2)


-0.6923076923076927


In [ ]:
input_data = ("12.9","14.82","1.8","14.82")

input_data_as_numpy_array = np.asarray(input_data)

input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

std_data = scaler.transform(input_data_reshaped)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if (prediction[0] == 0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')



